WITH DATA AS(
    SELECT SUM(AMOUNT) AS AMOUNT, PRODUCT_ID
    FROM FOOD_ORDER FO
    WHERE PRODUCE_DATE LIKE '%2022-05%'
    GROUP BY PRODUCT_ID
)
SELECT FP.PRODUCT_ID AS PRODUCT_ID, FP.PRODUCT_NAME AS PRODUCT_NAME, FP.PRICE * DATA.AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT FP, DATA
WHERE FP.PRODUCT_ID = DATA.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID