WITH DATA AS (
    SELECT MAX(PRICE) AS MAX_PRICE, CATEGORY
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
SELECT FP.CATEGORY, FP.PRICE, FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP, DATA
WHERE FP.PRICE = DATA.MAX_PRICE
AND FP.CATEGORY = DATA.CATEGORY
AND FP.CATEGORY IN ("과자", "국", "김치", "식용유")
ORDER BY FP.PRICE DESC